FROM node:20-alpine   
#lightweight Node image with npm
WORKDIR /app

# Copy only package files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app
COPY . .

# Expose the port your app uses
EXPOSE 4000

# Start your app
CMD ["npm", "run", "dev"]
